const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_FAIL = 'GET_FAIL';
const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNOUT';
const CREATE_REQUEST = 'CREATE_REQUEST';
const CREATE_SUCCEEDED = 'CREATE_SUCCEEDED';
const CREATE_FAILED = 'CREATE_FAILED';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ADD_TO_MY_LIST = 'ADD_TO_MY_LIST';
export const REMOVE_FROM_MY_LIST = 'REMOVE_FROM_MY_LIST';

export {
  GET_SUCCESS,
  GET_FAIL,
  GET_REQUEST,
  USER_SIGNIN,
  USER_SIGNOUT,
  CREATE_REQUEST,
  CREATE_SUCCEEDED,
  CREATE_FAILED,
};

export const logOut = () => ({ type: USER_SIGNOUT });
